var quotes = ['&ldquo;The future is scary, but you can&rsquo;t just run back to the past because it&rsquo;s familiar. Yes, it&rsquo;s tempting, but it&rsquo;s a mistake.&rdquo; &mdash; Robin Scherbatsky',
			   '&ldquo;Whenever I&rsquo;m sad, I stop being sad and be awesome instead.&rdquo; &mdash; Barney Stinson',
  '&ldquo;It&rsquo;s just, eventually, we&rsquo;re all gonna move on. It&rsquo;s called growing up.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;That cake. Best cake I ever had. Seriously, my stomach was like, &lsquo;Hey bro, I don&rsquo;t know what you&rsquo;re eating cause I don&rsquo;t have any eyes but it&rsquo;s basically awesome, so keep sending it down Gullet Alley.&rsquo;&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;Everyone has an opinion on how long it takes to recover from a breakup.&rdquo; &mdash; Ted Mosby',
  '&ldquo;I realized that I&rsquo;m searching, searching for what I really want in life. And you know what? I have absolutely no idea what that is.&rdquo; &mdash; Barney Stinson',
  '&ldquo;Because sometimes even if you know how something&rsquo;s gonna end, that doesn&rsquo;t mean you can&rsquo;t enjoy the ride.&rdquo; &mdash; Ted Mosby',
  '&ldquo;That&rsquo;s life, you know. We never end up where you thought you wanted to be.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;Oh my god, look at you cowards. So afraid of any kind of change. So terrified of anything new. So, so desperate to cling to anything comfortable and familiar.&rdquo; &mdash; Robin Scherbatsky',
  '&ldquo;A lie is just a great story that someone ruined with the truth.&rdquo; &mdash; Barney Stinson',
  '&ldquo;The three-day rule is a childish, manipulative mind game. But yeah, you wait three days.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;I get recognized one time, and I start thinking I&rsquo;m Julia Roberts. I&rsquo;m no VIP; I&rsquo;m not even an IP; I&rsquo;m just a lonely little P sitting out here in the gutter.&rdquo; &mdash; Robin Scherbatsky',
  '&ldquo;Every Halloween, I bring a spare costume, in case I strike out with the hottest girl at the party. That way, I have a second chance to make a first impression.&rdquo; &mdash; Barney Stinson',
  '&ldquo;Revenge fantasies never work out the way you want.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;So really the biggest mistake would be not to make that mistake, because then you&rsquo;ll go your whole life not knowing if something was a mistake or not.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;I finally found the one, Marshall. Her name is Bacon.&rdquo; &mdash; Ted Mosby',
  '&ldquo;The best I can give you is a fake smile and dead eyes.&rdquo; &mdash; Robin Scherbatsky',
  '&ldquo;I realized that I&rsquo;m searching, searching for what I really want in life. And you know what? I have absolutely no idea what that is.&rdquo; &mdash; Barney Stinson',
  '&ldquo;I&rsquo;ve never asked Lily to do anything &lsquo;no questions asked&rsquo; because I never wanted to. She&rsquo;s the love of my life. I never keep anything from her.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;Your package has always been big enough. You may not realize this, Marshall Eriksen, but you&rsquo;ve got a huge package.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;Look, I know the odds are the love of my life isn&rsquo;t going to magically walk through that door in a pumpkin costume at 2:43 in the morning. But it just seems as nice a spot as any to just, you know, sit and wait.&rdquo; &mdash; Ted Mosby',
  '&ldquo;Somewhere along the line, I forgot to pursue my dream, and now I&rsquo;m old, and I&rsquo;m a mom, and it&rsquo;s just too late for me.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;Whether a gesture&rsquo;s charming or alarming depends on how it&rsquo;s received.&rdquo; &mdash; Ted Mosby',
  '&ldquo;Lily, there are a million reasons why I love you. You make me laugh, you take care of me when I&rsquo;m sick, you&rsquo;re sweet, caring and you even created an egg dish and named it after me. She puts a little Italian dressing on the eggs before she cooks them, it&rsquo;s called Eggs Marshall and it&rsquo;s awesome. But the main reason is you&rsquo;re my best friend, Lily. You&rsquo;re the best friend I&rsquo;ve ever had.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;If I ask you to change too many things about yourself, you&rsquo;re not gonna be the man I fell in love with. Turns out I accept and appreciate even the grossest, creepiest, most sociopathic parts of you.&rdquo; &mdash; Robin Scherbatsky',
  '&ldquo;Maybe this isn&rsquo;t a breakup. Maybe this is just two friends getting back together.&rdquo; &mdash; Barney Stinson',
  '&ldquo;Definitions are important.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;I really don&rsquo;t like feelings.&rdquo; &mdash; Robin Scherbatsky',
  '&ldquo;I&rsquo;m cuddly. Deal with it.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;The only reason to wait a month for sex is if she&rsquo;s 17 years, 11 months old.&rdquo; &mdash; Barney Stinson',
  '&ldquo;Shouldn&rsquo;t we hold out for the person who doesn&rsquo;t just tolerate our little quirks, but actually kind of likes them?&rdquo; &mdash; Ted Mosby',
  '&ldquo;We spend an hour arguing about where to eat, and we end up here, anyway. I haven&rsquo;t eaten for two days. Can we please, for the love of God, just order something now?&rdquo; &mdash; Robin Scherbatsky',
  '&ldquo;I&rsquo;m a good boyfriend in my sleep.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;Believe it or not, I was not always as awesome as I am today.&rdquo; &mdash; Barney Stinson',
  '&ldquo;Some couples always support each other, and some couples always challenge each other. But is one really better than the other? Yes. Support is better. Way better.&rdquo; &mdash; Future Ted Mosby',
  '&ldquo;In marriage, being right is less important than being supportive. Remember: Happy wife equals happy life.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;I don&rsquo;t know where I&rsquo;m gonna be in five years. I don&rsquo;t wanna know. I want my life to be an adventure.&rdquo; &mdash; Robin Scherbatsky',
  '&ldquo;You have to let me dance my own battles.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;I used to be in such a hurry all the time. Everything was so urgent. Now I figure, if it&rsquo;s going to happen, it&rsquo;ll happen when it happens. I&rsquo;m not going anywhere; she&rsquo;s not going anywhere. What&rsquo;s the rush, right?&rdquo; &mdash; Ted Mosby',
  '&ldquo;You know what Marshall needs to do. He needs to stop being sad. When I get sad, I stop being sad and be awesome instead. True story.&rdquo; &mdash; Barney Stinson',
  '&ldquo;Oprah wasn&rsquo;t built in a day.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;If you keep giving up on people so quickly, you&rsquo;re gonna miss out on something great.&rdquo; &mdash; Robin Scherbatsky',
  '&ldquo;You will be shocked, kids, when you discover how easy it is in life to part ways with people forever. That&rsquo;s why, when you find someone you want to keep around, you do something about it.&rdquo; &mdash; Ted Mosby',
  '&ldquo;Death is all around us.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;Article 24: &ldquo;When wearing a baseball cap, a Bro may position the brim at either 12 or 6 o&rsquo;clock. All other angles are reserved for rappers and the handicapped.&rdquo; &mdash; Barney Stinson',
  '&ldquo;The more you fight it, the worse it&rsquo;s gonna get. It&rsquo;s like when your car slides on ice, you stir into the skid.&rdquo; &mdash; Ted Mosby',
  '&ldquo;You&rsquo;re my best friend. I don&rsquo;t need objectivity. I just need your support.&rdquo; &mdash; Lily Aldrin',
  '&ldquo;I thought I saw Big Foot in the park, so I tackled him.&rdquo; &mdash; Marshall Eriksen',
  '&ldquo;Kids, when you&rsquo;re in a new relationship and you&rsquo;re competing with your ex for who&rsquo;s happier, it can get ugly.&rdquo; &mdash; Ted Mosby',
  '&ldquo;Say goodbye to all the times you felt lost, to all the times it was a No instead of a Yes, to all the scrapes and bruises, to all the heartache.&rdquo; &mdash; Lily Aldrin'




]
function newQuote() {
var randomNumber = Math.floor(Math.random() * (quotes.length));
document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}